### ISSUE TITLE
Add ability to filter by type

### ISSUE THREAD

**Issue by jlandells** [vish9812/analog#12]
Often we either only want to show "Error" messages, or maybe we just want to filter out debug messages.  If you be great if this utility could understand what log levels are present in a log file, then give us checkboxes as to which ones we want to see.

**Comment by vish9812** [comment]
@jlandells If you want to just focus on errors, there is already a "toggle" specifically for errors. And if you want to filter-out other levels like DEBUG, you can also achieve that with the search box. Furthermore, you can make any no. of combinations with the "Contains" and "Not Contains".

![analog1](https://github.com/user-attachments/assets/d16c7fbf-b69f-49a5-b213-4a017e40931d)

**Comment by jlandells** [comment]
I found the filters to not give the results I expected, so was hoping for check boxes that simply allow me to select any combination of log level. On 19 Jul 2024, at 07:32, Vishal ***@***.***> wrote:﻿
@jlandells If you want to just focus on errors, there is already a "toggle" specifically for errors. And if you want to filter-out other levels like DEBUG, you can also achieve that with the search box. Furthermore, you can make any combinations with the "Contains" and "Not Contains".
analog1.png (view on web)

**Comment by vish9812** [comment]
Actually, it would be good to fix the search itself. Can you share what's not working correctly?

**Comment by vish9812** [comment]
@jlandells  With this PR - https://github.com/vish9812/analog/pull/13 , you can now search with "level" field and "debug" value.
